### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/curriculum-vitae#1]
- [ ] add https://kpi.ua/ntsa http://ssa.org.ua/ as first job (October 2010 - February 2011)
- [ ] add links to jobs to navigate on home pages
- [ ] fix languages through emoji
- [ ] fix errors
- [ ] add emoji to headers. who doesn't love icons? :)
